# Generated by Django 4.2 on 2023-04-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_outbound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X-Large'), ('F', 'Free')], max_length=2, verbose_name='사이즈'),
        ),
    ]
