# Generated by Django 4.2 on 2023-04-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='follow',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.CharField(default='', max_length=256),
        ),
    ]
